vscode:
  extensions:
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - ecmel.vscode-html-css@1.9.1:IxAxIfaC6OW70vfl5VyKbg==
    - anteprimorac.html-end-tag-labels@0.6.0:Mm/oQG5MYO/W/AD2YEUQxw==